# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bb0174ec2b4eab9f3b03ff5b258ff8cd559dc34eeae9a20aedaac17a69193860ce01e962ce71af50fb18b80098fc3328fa533b7faf4a0f0baeec7379eb8e1143

test:
  secret_key_base: df323596143a45f0537b3efdc96a40d7f76d6d2f1e18e86976ab71dd2a9080b4ecde391705d3875a0a65686b0f9110e520bf49628131aa941e47a4664736c3c7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
